apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: sync-secrets
  annotations:
    policies.kyverno.io/title: "Sync Secrets Across Namespaces"
spec:
  background: true
  rules:
    - name: sync-dev-secrets
      match:
        resources:
          kinds:
            - Secret
          namespaces:
            - dev
      synchronize:
        namespaceSelector:
          matchExpressions:
            - key: team
              operator: In
              values:
                - dev
