apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: add-imagepullsecret
  annotations:
    policies.kyverno.io/title: "Inject imagePullSecrets"
spec:
  rules:
    - name: add-imagepullsecret-to-deployments
      match:
        resources:
          kinds:
            - Deployment
      mutate:
        patchStrategicMerge:
          spec:
            template:
              spec:
                imagePullSecrets:
                  - name: my-private-registry
